# Generated by Django 5.1 on 2024-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='users/images'),
        ),
    ]
