# Generated by Django 5.1 on 2024-10-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='date_format',
            field=models.CharField(choices=[('MM/DD/YY', 'DD/MM/YY')], default='MM/DD/YY', max_length=30),
            preserve_default=False,
        ),
    ]
