# Generated by Django 5.1 on 2024-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
