# Generated by Django 5.1 on 2024-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('Full Day', '8 Hours'), ('Half Day', '4 Hours')], max_length=40)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
