# Generated by Django 5.1 on 2024-09-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayOff',
            new_name='Holiday',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
