# Generated by Django 5.1 on 2024-09-04 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0003_rename_dayoff_holiday_alter_employee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='amount',
            new_name='hours',
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.employee')),
            ],
        ),
    ]
