# Generated by Django 5.1 on 2024-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0004_rename_amount_holiday_hours_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('state', models.CharField(choices=[('Done', 'Done'), ('Review', 'Review'), ('Initial', 'Initial')], max_length=30)),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='recruiters/images')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('_', '_')], default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='HR', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Full-Time', max_length=100),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
