# Generated by Django 5.1 on 2024-10-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0005_recruitment_absence_reason_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='last_name',
            field=models.CharField(default='hasan', max_length=100),
            preserve_default=False,
        ),
    ]
