# Generated by Django 5.1 on 2024-10-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0006_rename_name_recruitment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('Finance', 'Finance')], default='HR', max_length=100),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=100),
        ),
    ]
