# Generated by Django 5.1 on 2024-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0007_alter_employee_department_alter_recruitment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='recruitment/resumes'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Initial', max_length=100),
        ),
    ]
