# Generated by Django 5.1 on 2024-10-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tool', '0008_recruitment_resume_alter_recruitment_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('progress', models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='0%', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_tool.skill')),
            ],
        ),
    ]
